#!/usr/bin/env node
/* Builds the two-file deployment in dist/:
     dist/index.html — page with the shared + bank files inlined
     dist/Code.gs    — backend with the shared + bank files appended
   Run after editing any source file: node tools/build-single.js */
"use strict";
const fs=require("fs"),path=require("path");
const ROOT=path.join(__dirname,".."),DIST=path.join(ROOT,"dist");
const SHARED=["cbt-shared.js","cbt-bank-permsec.js","cbt-bank-law-enforcement.js"];
const read=f=>fs.readFileSync(path.join(ROOT,f),"utf8");
fs.mkdirSync(DIST,{recursive:true});

/* index.html: swap each <script src="X"> for an inline copy of X */
let html=read("index.html");
for(const f of SHARED){
  const src=read(f);
  if(/<\/script/i.test(src))throw new Error(f+" contains </script and cannot be inlined");
  const tag=`<script src="${f}"></script>`;
  if(!html.includes(tag))throw new Error("index.html has no "+tag);
  html=html.replace(tag,()=>`<script>\n/* ---- inlined from ${f} ---- */\n${src}\n</script>`);
}
html=html.replace(/<!-- Shared data and logic[\s\S]*?-->\n/,"<!-- Single-file build: shared data and question banks are inlined below (generated by tools/build-single.js). -->\n");
html=html.replace('document.body.innerHTML=\'<p style="padding:2rem;font-family:sans-serif">cbt-shared.js could not be loaded. Keep cbt-shared.js, cbt-bank-permsec.js and cbt-bank-law-enforcement.js in the same folder as index.html.</p>\';',
  'document.body.innerHTML=\'<p style="padding:2rem;font-family:sans-serif">The page failed to load its question data. Re-upload index.html.</p>\';');
fs.writeFileSync(path.join(DIST,"index.html"),html);

/* Code.gs: one script file holding everything */
let gs=read("Code.gs").replace(/   The project needs FOUR script files:[\s\S]*?\(contents of cbt-bank-law-enforcement\.js\)\n\n/,
  "   SINGLE-FILE BUILD: this one Code.gs contains everything (shared data and\n   question banks are appended at the bottom). It is the only script file the\n   project needs.\n\n");
for(const f of SHARED)gs+=`\n\n/* ==================== inlined from ${f} ==================== */\n`+read(f);
fs.writeFileSync(path.join(DIST,"Code.gs"),gs);

console.log("Built dist/index.html ("+Math.round(html.length/1024)+" KB) and dist/Code.gs ("+Math.round(gs.length/1024)+" KB)");
